config/routes.rb
Rails.application.routes.draw do
  resources :source_mappings do
    member do
      get 'mapping'
    end
  end

  resources :db_connections do
    member do
      get 'tables'
    end
  end

  root 'db_connections#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/csv_file.rb
require 'csv'

class CsvFile

  attr_accessor :file_path

  def initialize(file_path)
    @file_path = file_path
  end

  def read; end

  def write(keys, array)
    CSV.open(file_path, "wb") do |csv|
      csv << keys
      array.each do |row|
        row_values = keys.map {|key| row[key] }
        csv << row_values
      end
    end
  end

end

app/models/db_connection.rb
require 'transproc/array'

class DbConnection < ApplicationRecord

  include Transproc::Helper

  def table_list
    fn = transform >> t(:extract_key, :tablename)
    fn.call(query('SELECT * FROM pg_catalog.pg_tables order by tablename')).delete_if {|i| i.match(/^pg_/)}
  end

  def tables_and_columns
    {}.tap do |rtn_hsh|
      table_list.sort.each do |table|
        rtn_hsh[table] = table_columns(table)
      end
    end
  end

  def table_columns(table)
    transform.call(
      query("select column_name, data_type, character_maximum_length from INFORMATION_SCHEMA.COLUMNS where table_name = '#{table}'")
    )
  end

  def load_data(table, columns=['*'], limit=1000)
    transform.call(
      query("select #{columns.join(',')} from #{table} limit #{limit}" )
    )
  end

  private

  def transform
    t(:map_array, t(:symbolize_keys))
  end

  def query(sql)
    conn = PG::Connection.open(
      dbname: database_name,
      host: database_host,
      user: database_user,
      port: database_port,
      connect_timeout: 2
    )
    result = conn.exec(sql)
    conn.close
    result
  end

end

app/models/source_mapping.rb
class SourceMapping < ApplicationRecord
  belongs_to :source, class_name: 'DbConnection'
  #belongs_to :destination, class_name: 'CsvFile'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/db_connections_controller.rb
class DbConnectionsController < ApplicationController
  before_action :set_db_connection, only: [:show, :edit, :update, :destroy, :tables]

  # GET /db_connections
  # GET /db_connections.json
  def index
    @db_connections = DbConnection.all
  end

  # GET /db_connections/1
  # GET /db_connections/1.json
  def show
  end

  # GET /db_connections/new
  def new
    @db_connection = DbConnection.new
  end

  # GET /db_connections/1/edit
  def edit
  end

  # POST /db_connections
  # POST /db_connections.json
  def create
    @db_connection = DbConnection.new(db_connection_params)

    respond_to do |format|
      if @db_connection.save
        format.html { redirect_to @db_connection, notice: 'Db connection was successfully created.' }
        format.json { render :show, status: :created, location: @db_connection }
      else
        format.html { render :new }
        format.json { render json: @db_connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /db_connections/1
  # PATCH/PUT /db_connections/1.json
  def update
    respond_to do |format|
      if @db_connection.update(db_connection_params)
        format.html { redirect_to @db_connection, notice: 'Db connection was successfully updated.' }
        format.json { render :show, status: :ok, location: @db_connection }
      else
        format.html { render :edit }
        format.json { render json: @db_connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /db_connections/1
  # DELETE /db_connections/1.json
  def destroy
    @db_connection.destroy
    respond_to do |format|
      format.html { redirect_to db_connections_url, notice: 'Db connection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /db_connections/1/tables
  # GET /db_connections/1/tables.json
  def tables
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_db_connection
      @db_connection = DbConnection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def db_connection_params
      params.require(:db_connection).permit(:name, :database_name, :database_host, :database_user, :database_port, :type)
    end
end

app/controllers/source_mappings_controller.rb
class SourceMappingsController < ApplicationController
  before_action :set_source_mapping, only: [:show, :edit, :update, :destroy, :mapping]

  # GET /source_mappings
  # GET /source_mappings.json
  def index
    @source_mappings = SourceMapping.all
  end

  # GET /source_mappings/1
  # GET /source_mappings/1.json
  def show
  end

  # GET /source_mappings/new
  def new
    @source_mapping = SourceMapping.new
  end

  # GET /source_mappings/1/edit
  def edit
  end

  # POST /source_mappings
  # POST /source_mappings.json
  def create
    @source_mapping = SourceMapping.new(source_mapping_params)

    respond_to do |format|
      if @source_mapping.save
        format.html { redirect_to mapping_source_mapping_path(@source_mapping), notice: 'Source mapping was successfully created.' }
        format.json { render :show, status: :created, location: @source_mapping }
      else
        format.html { render :new }
        format.json { render json: @source_mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /source_mappings/1
  # PATCH/PUT /source_mappings/1.json
  def update
    respond_to do |format|
      if @source_mapping.update(source_mapping_params)
        format.html { redirect_to @source_mapping, notice: 'Source mapping was successfully updated.' }
        format.json { render :show, status: :ok, location: @source_mapping }
      else
        format.html { render :edit }
        format.json { render json: @source_mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /source_mappings/1
  # DELETE /source_mappings/1.json
  def destroy
    @source_mapping.destroy
    respond_to do |format|
      format.html { redirect_to source_mappings_url, notice: 'Source mapping was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def mapping
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source_mapping
      @source_mapping = SourceMapping.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def source_mapping_params
      params.require(:source_mapping).permit(:source_id, :destination_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/db_connections_helper.rb
module DbConnectionsHelper
end

app/helpers/source_mappings_helper.rb
module SourceMappingsHelper
end

app/views/db_connections/_form.html.erb
<%= form_for(db_connection) do |f| %>
  <% if db_connection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(db_connection.errors.count, "error") %> prohibited this db_connection from being saved:</h2>

      <ul>
      <% db_connection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :database_name %>
    <%= f.text_field :database_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :database_host %>
    <%= f.text_field :database_host, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :database_user %>
    <%= f.text_field :database_user, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :database_port %>
    <%= f.text_field :database_port, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :type %>
    <%= f.text_field :type, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/db_connections/edit.html.erb
<h1>Editing Db Connection</h1>

<%= render 'form', db_connection: @db_connection %>

<%= link_to 'Show', @db_connection %> |
<%= link_to 'Back', db_connections_path %>

app/views/db_connections/index.html.erb
<div class="row">
  <h1>Db Connections</h1>
</div>

<div class="row">
  <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Database name</th>
      <th>Database host</th>
      <th>Database user</th>
      <th>Database port</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @db_connections.each do |db_connection| %>
      <tr>
        <td><%= db_connection.name %></td>
        <td><%= db_connection.database_name %></td>
        <td><%= db_connection.database_host %></td>
        <td><%= db_connection.database_user %></td>
        <td><%= db_connection.database_port %></td>
        <td><%= db_connection.type %></td>
        <td><%= link_to 'Show', db_connection %></td>
        <td><%= link_to 'Edit', edit_db_connection_path(db_connection) %></td>
        <td><%= link_to 'Destroy', db_connection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Db Connection', new_db_connection_path %>
</row>

app/views/db_connections/new.html.erb
<h1>New Db Connection</h1>

<%= render 'form', db_connection: @db_connection %>

<%= link_to 'Back', db_connections_path %>

app/views/db_connections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @db_connection.name %>
</p>

<p>
  <strong>Database name:</strong>
  <%= @db_connection.database_name %>
</p>

<p>
  <strong>Database host:</strong>
  <%= @db_connection.database_host %>
</p>

<p>
  <strong>Database user:</strong>
  <%= @db_connection.database_user %>
</p>

<p>
  <strong>Database port:</strong>
  <%= @db_connection.database_port %>
</p>

<p>
  <strong>Type:</strong>
  <%= @db_connection.type %>
</p>

<%= link_to 'Edit', edit_db_connection_path(@db_connection) %> |
<%= link_to 'Back', db_connections_path %>

app/views/db_connections/tables.html.erb
<div class="row">
  <div class="col-md-12">
    <h1><%= @db_connection.name %> Tables</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <ul class="list-group">
    <% @db_connection.tables_and_columns.each_with_index do |(table, columns), index| %>
      <li class="list-group-item" id="table<%= index %>">
        <h5>
        <a class="collapsed" data-toggle="collapse" href="#tableColumns<%= index %>" aria-expanded="false" aria-controls="tableColumns<%= index %>">
          <%= table %>
        </a>
      </h5>
      </li>
      <li class="list-group-item">
        <ul class="list-group collapse" id="tableColumns<%= index %>" role="tabpanel" aria-labelledby="table<%= index %>">
          <% columns.each do |column| %>
            <li  class="list-group-item"><%= column[:column_name] %> (<%= column[:data_type] %>)</li>
          <% end %>
        </ul>
      </li>
    <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-inverse"> <!-- navbar-fixed-top -->
  <%= link_to "Data Syncer", root_path, class: "navbar-brand" %>
  <ul class="nav navbar-nav">

    <li class="nav-item <%= "active" if current_page?(controller: 'db_connections') %>">
      <%= link_to db_connections_path, class: ["nav-link"] do %>
        Data Connections <% if current_page?(controller: 'db_connections') %> <span class="sr-only">(current)</span> <% end %>
      <% end %>
    </li>
    <li class="nav-item <%= "active" if current_page?(controller: 'source_mappings') %>">
      <%= link_to source_mappings_path, class: ["nav-link"] do %>
        Source Mappings <% if current_page?(controller: 'source_mappings') %> <span class="sr-only">(current)</span> <% end %>
      <% end %>
    </li>


    <!-- <li class="nav-item">
      <a class="nav-link" href="#">About</a>
    </li> -->
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Data Syncer</title>
    <%= csrf_meta_tags %>

    <script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script><!-- Tether for Bootstrap -->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/source_mappings/_form.html.erb
<%= form_for(source_mapping) do |f| %>
  <% if source_mapping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(source_mapping.errors.count, "error") %> prohibited this source_mapping from being saved:</h2>

      <ul>
      <% source_mapping.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :source_id, 'Data Source' %>
    <%= f.select(:source_id, DbConnection.all.map{|d| [d.name, d.id]} + [['CSV', 0]], { include_blank: true }, { class: "form-control" }) %>
  </div>

  <div class="form-group">
    <%= f.label :destination_id, 'Data Destination' %>
    <%= f.select(:destination_id, DbConnection.all.map{|d| [d.name, d.id]} + [['CSV', 0]], { include_blank: true }, { class: "form-control" }) %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/source_mappings/edit.html.erb
<h1>Editing Data Mapping</h1>

<%= render 'form', source_mapping: @source_mapping %>

<%= link_to 'Show', @source_mapping %> |
<%= link_to 'Back', source_mappings_path %>

app/views/source_mappings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Source Mappings</h1>

<table>
  <thead>
    <tr>
      <th>Source</th>
      <th>Destination</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @source_mappings.each do |source_mapping| %>
      <tr>
        <td><%= source_mapping.source_id %></td>
        <td><%= source_mapping.destination_id %></td>
        <td><%= link_to 'Show', source_mapping %></td>
        <td><%= link_to 'Edit', edit_source_mapping_path(source_mapping) %></td>
        <td><%= link_to 'Destroy', source_mapping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Source Mapping', new_source_mapping_path %>

app/views/source_mappings/mapping.html.erb
<div class="row">
  <h1>Data Mapper</h1>
</div>

<div class="row">
  <div class="col-md-3 dataSource">
    <h3>Data Source</h3>
    <%= select_tag(:source_tables, options_for_select(@source_mapping.source.table_list.map{|d| [d, d]}), include_blank: true, class: "form-control dataSourceTableSelect") %>
    <% @source_mapping.source.tables_and_columns.each do |table, columns| %>
      <div class="card hidden" id="table-<%= table %>">
        <div class="card-block">
          <h4 class="card-title"><%= table %></h4>
          <ul class="list-group">
            <% columns.sort{|x,y| x[:column_name] <=> y[:column_name] }.each do |column| %>
              <li  class="list-group-item">
                <%= check_box_tag("#{table}[#{column[:column_name]}]", column[:column_name], false, class: 'sourceColumn') %>
                <%= column[:column_name] %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-md-6">
    <h3>Data Translation</h3>
    <table class="table dataTranslations">
      <thead>
        <tr>
          <th>From</th>
          <th>To</th>
          <th>Transformation</th>
          <th>Example</th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>

  <div class="col-md-3 csvFile">
    <h3>CSV File</h3>
    <div class="csvColumns">
    </div>
    <%= button_tag 'Add Column', class: 'addCsvColumnButton' %>
  </div>

</div>

app/views/source_mappings/new.html.erb
<h1>New Data Mapping</h1>

<%= render 'form', source_mapping: @source_mapping %>

<%= link_to 'Back', source_mappings_path %>

app/views/source_mappings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Source:</strong>
  <%= @source_mapping.source_id %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @source_mapping.destination_id %>
</p>

<%= link_to 'Edit', edit_source_mapping_path(@source_mapping) %> |
<%= link_to 'Back', source_mappings_path %>